# Generated by Django 5.2 on 2025-05-03 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante'),
        ),
    ]
