# Generated by Django 5.2 on 2025-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ultima_actividad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
