# Generated by Django 5.2 on 2025-04-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField()),
                ('importante', models.BooleanField()),
                ('usuarioid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estudiante')),
            ],
        ),
    ]
