# Generated by Django 5.2 on 2025-05-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventosAgenda', '0001_initial'),
        ('login', '0002_estudiante_ultima_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante'),
        ),
    ]
